### PR TITLE
Created CircleImageWithTitleMolecule

### LINKED ISSUE #18: Create CircleImageWithTitle molecule
**Have consistent headers for post**
We need to have consistent images, titles, and subtitles for all posts. This will be used over and over again so it makes sense to make it a reusable component.

**Create molecule that can be used for post headers**
Use material UI Typography and CircleImage atom to create a molecule that has a circular image on the left with a title on the right. It also has a subtitle below the title.

**Alternatives considered**
I considered not making this its own molecule and just having it in the post organism. However atomic design principles lead to making all components as small as possible. 

**Additional Context**
The subtitle and title length will change. Make sure styles are responsive and can handle this dynamic data.

### PR DESCRIPTION
**Pull request by transformerjnm**
Made the CircleImageWithTitleMolecule using the CircleImage atom and material UI typography component. It can display the image, title, and a subtitle. Designed to be used at the top of post as a post header.

### CODE REVIEW

**Review by Blaine137 — CHANGES_REQUESTED** [review]
Everything looks good besides a few small things...

subtitle should be camel cased due to our style guide and the circle image is not centered like it is on Facebook.

**Comment by transformerjnm** [comment]
I centered the image. Good catch Blaine! However, subtitle is one word so I don't think the letter t should be capitalized.

**Review by Blaine137 — APPROVED** [review]
Looks good!

**Review by ChadAltenberger — APPROVED** [review]
Looks clean

**Pull request merged**
