### PR TITLE
Created component for the nav links with styling for active class #12

### LINKED ISSUE #12: Create an NavigationIconLink atom
**Consistent styles for navigation links**
Create a reusable component that will ensure all navigation icon button links have consistent styles. 

**Material UI Icon button**
I think we should use a material UI icon button that has a child element of a react-router link. The page we are currently on should be blue and have an underline of blue.

**React Router alternative**
We could style a react-router link to look like an icon button. However, we have Material UI that provides an icon button. So why create one?

### PR DESCRIPTION
**Pull request by ChadAltenberger**
This is as close as I could get it. Might need some help. I can't get the container div surrounding the icon to link to the path as well without losing the active class styling.

### CODE REVIEW

**Review by Blaine137 — CHANGES_REQUESTED** [review]
Everything looks good, but I noticed that you made changes to the home page. please remove any changes made in that file. Goodjob Chad!!

**Review by transformerjnm — CHANGES_REQUESTED** [review]
Indent using tabs, not spaces.

The summary should not tell you what the props are. This component does not have the navigation bar styles so the summary should not say that it does.

Need to add children under the prop with a description of Icon to be displayed for the link. 

Unnecessary whitespace in between imports and we do not need whitespace in between the component level comment and the component. (line 18)

**Comment by ChadAltenberger** [comment]
> Everything looks good, but I noticed that you made changes to the home page. please remove any changes made in that file. Goodjob Chad!!

Ok, thanks! On the HomePage.js, I added the imports for the MUI icons we'll need to pass in for the nav links and just commented them out for now. Would you still like me to delete those?

**Comment by ChadAltenberger** [comment]
> Indent using tabs, not spaces.
> 
> The summary should not tell you what the props are. This component does not have the navigation bar styles so the summary should not say that it does.
> 
> Need to add children under the prop with a description of Icon to be displayed for the link.
> 
> Unnecessary whitespace in between imports and we do not need whitespace in between the component comment and the comment. (line 18)

Summary: So the reason I added what the props are is because it already had "props:" in the comments so I assumed I needed to add them. 

I'm not sure what you mean by adding children under the prop with a description of the icon. I thought the icons would be added in on the home page when we actually render the NavigationLinkIcon component?

Not sure what you mean by no whitespace in between component comment and comment?

**Comment by transformerjnm** [comment]
Note Blaine worked on the component some. The icon was switched from being passed in as a named prop to being passed in though props.children. Once he changed this he forgot to add it to the component level comment under the props section in the comment.

That was a typo it should be "Unnecessary whitespace in between imports and we do not need whitespace in between the component level comment and the component."

**Review by Blaine137 — APPROVED** [review]

**Review by transformerjnm — APPROVED** [review]

**Pull request merged**
