### PR TITLE
Gk font sizes

### LINKED ISSUE #7: Material UI fluid font sizes
** Font sizes that are consistent and fluid **
We need font sizes to be consistent across the entire application and to have fluid typography. Fluid meaning with no breakpoints that it calculated the font size for each screen size.

** Material UI Theme Font Sizes **
We should declare font sizes for each typography variant in Material UI. We can achieve fluid typography by using the calc() function. 

** Alternatives Considered **
I considered using breakpoint for responsive typography however fluid typography with no breakpoints offers a better user experience.

** Font Sizes **
The font sizes should be based on Facebook font sizes for specific elements like H1.

### PR DESCRIPTION
**Pull request by gkourako**
I'm 90% sure this works. Can someone review it to make sure it meets the standard?  I added some mock text and a button to the home page.It looks fluid to me, but tear it apart and tell me what i've done wrong.

### CODE REVIEW

**Review by transformerjnm — CHANGES_REQUESTED** [review]
Improper code format on line 21. 

H6 should have a second value in the calc function that is greater than 0. Since it is zero the font size never changes based on screen width.

Body text needs to be readable. It is too small, currently it is like the height that people use for copyright text in footers.

The font size is calculated by descending numbers. One percent less for each one. Does this match facebook's font sizes? Does this use some kinda font theory for sizes? Inspect the code for facebook and find their font sizes. For uncertain font sizes, use font theories to ensure font sizes work well together. Visit this site for help with font theory. https://type-scale.com/ Note theories are kinda like guides and can be flexible. 

What is this change for package-lock.json? Did you update or install a package? I don't see you using anything new?

remove test code from the home page before pushing.

**Review by Blaine137 — CHANGES_REQUESTED** [review]
You should have modified only one file for your issue. Please remove all the code you added from the home page and remove any packages you installed.

**Review by transformerjnm — CHANGES_REQUESTED** [review]
Font sizes still seem not a long way off from Facebook font sizes. What page did you get your font sizes from on Facebook?

Still unsure of why the package-lock.json changed. Looking at the dependencies in the package.json file it does not appear you installed any packages. Did you run npm audit fix? I don’t think it should break anything just would like to know why it's different. Possibly using different versions then us.

**Comment by gkourako** [comment]
> Improper code format on line 21.
> 
> H6 should have a second value in the calc function that is greater than 0. Since it is zero the font size never changes based on screen width.
> 
> Body text needs to be readable. It is too small, currently it is like the height that people use for copyright text in footers.
> 
> The font size is calculated by descending numbers. One percent less for each one. Does this match facebook's font sizes? Does this use some kinda font theory for sizes? Inspect the code for facebook and find their font sizes. For uncertain font sizes, use font theories to ensure font sizes work well together. Visit this site for help with font theory. https://type-scale.com/ Note theories are kinda like guides and can be flexible.
> 
> What is this change for package-lock.json? Did you update or install a package? I don't see you using anything new?
> 
> remove test code from the home page before pushing.

I didn't mean to re request a code review.  I inspected the page in multiple places and kept getting 15px. 1 rem is 16 so I put it .80 Rem. Blaine and I discussed the npm packages

**Review by transformerjnm — APPROVED** [review]

**Review by Blaine137 — APPROVED** [review]

**Pull request merged**
